
export interface ColourVariant {
  name: string;
  slug: string;
  hex: string;
  indexCode: string;
  primaryCostPerSqFt: number;
  sqftPerBox: number;
  mrpPerBoxInclGst: number;
  addShippingCharge: number;
  priceAfterShipping: number;
  discMarginPercent: number;
  priceAfterDiscMargin: number;
  installCharge: number;
  priceAfterInstall: number;
  finalMrpPerBox: number;
  perSqFt: number;
  displayPrice: number;
  perSqFtDiscount: number;
}

export interface CollectionData {
  id: string;
  name: string;
  description: string[];
  dimensions: { width: string; height: string; thickness: string };
  boxSpecs: { each_box_contains: string; each_box_area: string; qty: string };
  features: string[];
  price: number;
  sku: string;
  colours: ColourVariant[];
}

export const collections: Record<string, CollectionData> = {
  "s-line": {
    id: "s-line",
    name: "S-Line",
    description: [
      `Linerio S-Line slatted panels make your room taller and cozier. VOX S-Line Linerio Panels have the narrowest lamellas in the category. Linerio panels are lightweight, durable, and allow flexibility in design. They come with a 2-year VOX Warranty.`,
      `Linerio panels improve acoustics in your room. They are scratch- and stain-resistant, and are made from 100% recyclable material. Linerio’s water-resistant capabilities allow its use in bathrooms.`,
      `Linerio makes great dirt-resistant walls – greasy cosmetics, wet pet hair or dirty hands of a toddler on them are not something to worry about. They will last for years with no special care. Wiping them with a moist cloth is all they need.`,
      `Installation of Linerio panels is quick and easy. Cut your panel into the required size and glue it straight to the wall or ceiling. Linerio panels can be installed vertically, horizontally or diagonally depending on your design. Immediately after their installation, you can freely use the room.`
    ],
    dimensions: { width: "122 mm", height: "3050 mm", thickness: "12 mm" },
    boxSpecs:{each_box_contains: "16 Panels", each_box_area: "64.08 sqft", qty: "1 box"},
    features: [
      "Sound-absorbing properties",
      "Lightweight construction",
      "Easy to clean",
      "Quick installation",
      "100% recyclable material",
    ],
    price: 49.99,
    sku: "SL",
    colours: [
      {
        name: "Mocca",
        slug: "mocca",
        hex: "#6F4E37",
        indexCode: "3031361",
        primaryCostPerSqFt: 331.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 21211.99,
        addShippingCharge: 1000.0,
        priceAfterShipping: 22211.99,
        discMarginPercent: 15,
        priceAfterDiscMargin: 25543.78,
        installCharge: 50,
        priceAfterInstall: 28748,
        finalMrpPerBox: 28799,
        perSqFt: 449,
        displayPrice: 25919,
        perSqFtDiscount: 404,
      },
      {
        name: "Natural",
        slug: "natural",
        hex: "#D2B48C",
        indexCode: "3031343",
        primaryCostPerSqFt: 331.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 21211.99,
        addShippingCharge: 1000.0,
        priceAfterShipping: 22211.99,
        discMarginPercent: 15,
        priceAfterDiscMargin: 25543.78,
        installCharge: 50,
        priceAfterInstall: 28748,
        finalMrpPerBox: 28799,
        perSqFt: 449,
        displayPrice: 25919,
        perSqFtDiscount: 404,
      },
      {
        name: "Natural Black",
        slug: "natural-black",
        hex: "#2C2C2C",
        indexCode: "3031415",
        primaryCostPerSqFt: 331.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 21211.99,
        addShippingCharge: 1000.0,
        priceAfterShipping: 22211.99,
        discMarginPercent: 15,
        priceAfterDiscMargin: 25543.78,
        installCharge: 50,
        priceAfterInstall: 28748,
        finalMrpPerBox: 28799,
        perSqFt: 449,
        displayPrice: 25919,
        perSqFtDiscount: 404,
      },
      {
        name: "White",
        slug: "white",
        hex: "#FFFFFF",
        indexCode: "3031377",
        primaryCostPerSqFt: 331.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 21211.99,
        addShippingCharge: 1000.0,
        priceAfterShipping: 22211.99,
        discMarginPercent: 15,
        priceAfterDiscMargin: 25543.78,
        installCharge: 50,
        priceAfterInstall: 28748,
        finalMrpPerBox: 28799,
        perSqFt: 449,
        displayPrice: 25919,
        perSqFtDiscount: 404,
      },
      {
        name: "Anthracite",
        slug: "anthracite",
        hex: "#383838",
        indexCode: "3031378",
        primaryCostPerSqFt: 331.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 21211.99,
        addShippingCharge: 1000.0,
        priceAfterShipping: 22211.99,
        discMarginPercent: 15,
        priceAfterDiscMargin: 25543.78,
        installCharge: 50,
        priceAfterInstall: 28748,
        finalMrpPerBox: 28799,
        perSqFt: 449,
        displayPrice: 25919,
        perSqFtDiscount: 404,
      },
      {
        name: "Grey",
        slug: "grey",
        hex: "#808080",
        indexCode: "3031379",
        primaryCostPerSqFt: 331.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 21211.99,
        addShippingCharge: 1000.0,
        priceAfterShipping: 22211.99,
        discMarginPercent: 15,
        priceAfterDiscMargin: 25543.78,
        installCharge: 50,
        priceAfterInstall: 28748,
        finalMrpPerBox: 28799,
        perSqFt: 449,
        displayPrice: 25919,
        perSqFtDiscount: 404,
      },
      {
        name: "Black",
        slug: "black",
        hex: "#000000",
        indexCode: "3031408",
        primaryCostPerSqFt: 331.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 21211.99,
        addShippingCharge: 1000.0,
        priceAfterShipping: 22211.99,
        discMarginPercent: 15,
        priceAfterDiscMargin: 25543.78,
        installCharge: 50,
        priceAfterInstall: 28748,
        finalMrpPerBox: 28799,
        perSqFt: 449,
        displayPrice: 25919,
        perSqFtDiscount: 404,
      },
    ],
  },

  "m-line": {
    id: "m-line",
    name: "M-Line",
    description: [
      `VOX Linerio M-Line slatted panels are the perfect fit for the demanding areas of your house. Linerio panels are lightweight, durable, and allow flexibility in design. They come with a 2-year VOX Warranty.`,
      `Through their high-quality material and its spatial structure, the panels help improve acoustics in your room and eliminate reverberation and echo in larger rooms. They are scratch- and stain-resistant, and are made from 100% recyclable material. Linerio’s water-resistant capabilities allow its use in bathrooms.`,
      `Linerio makes great dirt-resistant walls – greasy cosmetics, wet pet hair or dirty hands of a toddler on them are not something to worry about. They will last for years with no special care. Wiping them with a moist cloth is all they need.`,
      `Installation of Linerio panels is quick and easy. Cut your panel into the required size and glue it straight to the wall or ceiling. Linerio panels can be installed vertically, horizontally or diagonally depending on your design. Immediately after their installation, you can freely use the room.`
    ],
    dimensions: { width: "122 mm", height: "3050 mm", thickness: "12 mm" },
    boxSpecs:{each_box_contains: "16 Panels", each_box_area: "64.08 sqft", qty: "1 box"},
    features: [
      "Sound-absorbing properties",
      "Lightweight construction",
      "Easy to clean",
      "Quick installation",
      "100% recyclable material",
    ],
    price: 59.99,
    sku: "ML",
    colours: [
      {
        name: "Mocca",
        slug: "mocca",
        hex: "#6F4E37",
        indexCode: "3031363",
        primaryCostPerSqFt: 321.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 20571.14,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21571.14,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24806.81,
        installCharge: 50,
        priceAfterInstall: 28011,
        finalMrpPerBox: 28099,
        perSqFt: 438,
        displayPrice: 25289,
        perSqFtDiscount: 395,
      },
      {
        name: "Natural",
        slug: "natural",
        hex: "#D2B48C",
        indexCode: "3031362",
        primaryCostPerSqFt: 321.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 20571.14,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21571.14,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24806.81,
        installCharge: 50,
        priceAfterInstall: 28011,
        finalMrpPerBox: 28099,
        perSqFt: 438,
        displayPrice: 25289,
        perSqFtDiscount: 395,
      },
      {
        name: "Natural Black",
        slug: "natural-black",
        hex: "#2C2C2C",
        indexCode: "3031414",
        primaryCostPerSqFt: 321.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 20571.14,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21571.14,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24806.81,
        installCharge: 50,
        priceAfterInstall: 28011,
        finalMrpPerBox: 28099,
        perSqFt: 438,
        displayPrice: 25289,
        perSqFtDiscount: 395,
      },
      {
        name: "Chocolate",
        slug: "chocolate",
        hex: "#7B3F00",
        indexCode: "3031364",
        primaryCostPerSqFt: 321.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 20571.14,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21571.14,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24806.81,
        installCharge: 50,
        priceAfterInstall: 28011,
        finalMrpPerBox: 28099,
        perSqFt: 438,
        displayPrice: 25289,
        perSqFtDiscount: 395,
      },
      {
        name: "White",
        slug: "white",
        hex: "#FFFFFF",
        indexCode: "3031374",
        primaryCostPerSqFt: 321.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 20571.14,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21571.14,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24806.81,
        installCharge: 50,
        priceAfterInstall: 28011,
        finalMrpPerBox: 28099,
        perSqFt: 438,
        displayPrice: 25289,
        perSqFtDiscount: 395,
      },
      {
        name: "Anthracite",
        slug: "anthracite",
        hex: "#383838",
        indexCode: "3031375",
        primaryCostPerSqFt: 321.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 20571.14,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21571.14,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24806.81,
        installCharge: 50,
        priceAfterInstall: 28011,
        finalMrpPerBox: 28099,
        perSqFt: 438,
        displayPrice: 25289,
        perSqFtDiscount: 395,
      },
      {
        name: "Grey",
        slug: "grey",
        hex: "#808080",
        indexCode: "3031376",
        primaryCostPerSqFt: 321.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 20571.14,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21571.14,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24806.81,
        installCharge: 50,
        priceAfterInstall: 28011,
        finalMrpPerBox: 28099,
        perSqFt: 438,
        displayPrice: 25289,
        perSqFtDiscount: 395,
      },
      {
        name: "Black",
        slug: "black",
        hex: "#000000",
        indexCode: "3031407",
        primaryCostPerSqFt: 321.0,
        sqftPerBox: 64.08,
        mrpPerBoxInclGst: 20571.14,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21571.14,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24806.81,
        installCharge: 50,
        priceAfterInstall: 28011,
        finalMrpPerBox: 28099,
        perSqFt: 438,
        displayPrice: 25289,
        perSqFtDiscount: 395,
      },
    ],
  },

  "l-line": {
    id: "l-line",
    name: "L-Line",
    description: [
      `The deep slats of VOX Linerio L-Line Panels are the statement décor of your space. They provide a distinctive focal point that works best on large walls in spacious interiors.`,
      `These VOX panels are lightweight, durable, and allow flexibility in design. They come with a 2-year VOX Warranty.`,
      `Through Linerio’s high-quality material and its spatial structure, the panels help improve acoustics in your room and eliminate reverberation and echo in larger rooms. They are scratch- and stain-resistant, and are made from 100% recyclable material. Linerio’s water-resistant capabilities allow its use in bathrooms.`,
      `Linerio makes great dirt-resistant walls – greasy cosmetics, wet pet hair or dirty hands of a toddler on them are not something to worry about. They will last for years with no special care. Wiping them with a moist cloth is all they need.`,
      `Installation of Linerio panels is quick and easy. Cut your panel into the required size and glue it straight to the wall or ceiling. Linerio panels can be installed vertically, horizontally or diagonally depending on your design. Immediately after their installation, you can freely use the room.`
    ],
    dimensions: { width: "122 mm", height: "3050 mm", thickness: "21 mm" },
    boxSpecs:{each_box_contains: "12 Panels", each_box_area: "48.06 sqft", qty: "1 box"},
    features: [
      "Sound-absorbing properties",
      "Lightweight construction",
      "Easy to clean",
      "Quick installation",
      "100% recyclable material",
    ],
    price: 69.99,
    sku: "LL",
    colours: [
      {
        name: "Mocca",
        slug: "mocca",
        hex: "#6F4E37",
        indexCode: "3031366",
        primaryCostPerSqFt: 427.0,
        sqftPerBox: 48.06,
        mrpPerBoxInclGst: 20523.08,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21523.08,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24751.54,
        installCharge: 50,
        priceAfterInstall: 27155,
        finalMrpPerBox: 27199,
        perSqFt: 566,
        displayPrice: 24479,
        perSqFtDiscount: 509,
      },
      {
        name: "Natural",
        slug: "natural",
        hex: "#D2B48C",
        indexCode: "3031365",
        primaryCostPerSqFt: 427.0,
        sqftPerBox: 48.06,
        mrpPerBoxInclGst: 20523.08,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21523.08,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24751.54,
        installCharge: 50,
        priceAfterInstall: 27155,
        finalMrpPerBox: 27199,
        perSqFt: 566,
        displayPrice: 24479,
        perSqFtDiscount: 509,
      },
      {
        name: "Chocolate",
        slug: "chocolate",
        hex: "#7B3F00",
        indexCode: "3031367",
        primaryCostPerSqFt: 427.0,
        sqftPerBox: 48.06,
        mrpPerBoxInclGst: 20523.08,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21523.08,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24751.54,
        installCharge: 50,
        priceAfterInstall: 27155,
        finalMrpPerBox: 27199,
        perSqFt: 566,
        displayPrice: 24479,
        perSqFtDiscount: 509,
      },
      {
        name: "White",
        slug: "white",
        hex: "#FFFFFF",
        indexCode: "3031380",
        primaryCostPerSqFt: 427.0,
        sqftPerBox: 48.06,
        mrpPerBoxInclGst: 20523.08,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21523.08,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24751.54,
        installCharge: 50,
        priceAfterInstall: 27155,
        finalMrpPerBox: 27199,
        perSqFt: 566,
        displayPrice: 24479,
        perSqFtDiscount: 509,
      },
      {
        name: "Anthracite",
        slug: "anthracite",
        hex: "#383838",
        indexCode: "3031381",
        primaryCostPerSqFt: 427.0,
        sqftPerBox: 48.06,
        mrpPerBoxInclGst: 20523.08,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21523.08,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24751.54,
        installCharge: 50,
        priceAfterInstall: 27155,
        finalMrpPerBox: 27199,
        perSqFt: 566,
        displayPrice: 24479,
        perSqFtDiscount: 509,
      },
      {
        name: "Grey",
        slug: "grey",
        hex: "#808080",
        indexCode: "3031382",
        primaryCostPerSqFt: 427.0,
        sqftPerBox: 48.06,
        mrpPerBoxInclGst: 20523.08,
        addShippingCharge: 1000.0,
        priceAfterShipping: 21523.08,
        discMarginPercent: 15,
        priceAfterDiscMargin: 24751.54,
        installCharge: 50,
        priceAfterInstall: 27155,
        finalMrpPerBox: 27199,
        perSqFt: 566,
        displayPrice: 24479,
        perSqFtDiscount: 509,
      },
    ],
  },
};
